# Reference:
#   https://github.com/wikimedia/parsoid/blob/v0.9.0/config.example.yaml

num_workers: 1
worker_heartbeat_timeout: 300000
logging:
    level: info
services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        mwApis:
        - uri: 'MEDIAWIKI_APIS_URI'
          domain: 'MEDIAWIKI_APIS_DOMAIN'
        useSelser: true
        serverInterface: '0.0.0.0'
